# Generated by Django 2.2.25 on 2022-01-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_worlds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='worlds',
            new_name='words',
        ),
    ]
